export * from "./header"
export * from "./hero"
export * from "./about-project"
export * from "./tech-stack"
export * from "./how-works"
export * from "./cta"
export * from "./architecture"
export * from "./footer"